### ISSUE TITLE
Geoserver auth not working on lbimsgis

### ISSUE THREAD

**Issue by gubuntu** [kartoza/LEDET_BIMS#155]
If I log in to GeoNode and go to Geoserver admin, it doesn't log in. 

Neither can I use any OWS

child of #4

**Comment by NyakudyaA** [comment]
@gubuntu  I am investigating why it doesn't log you in but the OWS service is working from metasearch in QGIS.
Here is a sample layer added with my geonode credentials in metasearch
![ows](https://user-images.githubusercontent.com/2510900/42514931-d7348622-845a-11e8-9e12-37aa41949e3e.png)

**Comment by gubuntu** [comment]
I tried adding WMS and WFS and also the GeoNode provider and none of them worked.

**Comment by NyakudyaA** [comment]
@gubuntu  I created an account for Warren and tested MetaSearch using his credentials and everything works as expected. The correct OWS request is  http://lbimsgis.kartoza.com//geoserver/geonode/ows 

I have fixed a couple of  the layer permissions and you should be able to see all layers

**Comment by gubuntu** [comment]
I still can't log into geoserver, even after creating a new superuser, not on firefox nor chrome. 

When I first tried on chrome I got a CSRF error, so please check nginx and django settings configs and turn debugging off

**Comment by gubuntu** [comment]
1. Have you changed something? Now I can do WMS and WFS and WCS connections to http://lbimsgis.kartoza.com/geoserver/ows from QGIS 3.2 with NO authentication (does removing the layers from public access in GeoNode not also require authentication on geoserver services?) 
1. The GeoNode provider still shows nothing
1. I still can't connect with SLD Editor
1. I still can't log into geoserver

**Comment by NyakudyaA** [comment]
This is now working in https://testing.limpopobims.kartoza.com so I will close this ticket
