### ISSUE TITLE
Profile page is broken

### ISSUE THREAD

**Issue by dimasciput** [kartoza/LEDET_BIMS#192]
![screen shot 2018-07-19 at 2 53 29 pm](https://user-images.githubusercontent.com/1979569/42929205-910c1f60-8b63-11e8-90be-61eb5509dfba.png)

@gubuntu, Should we just redirect it to the geonode profile page?

**Comment by gubuntu** [comment]
Yes we can probably use and extend geonode profile. @lucernae can probably give a better answer

**Comment by ann26** [comment]
It is fixed in https://github.com/kartoza/django-bims/pull/158

**Comment by gubuntu** [comment]
better but still not right
![Screen Shot 2018-08-07 at 20.59.25.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba46167953d2fd0f723be0/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6454f46b7191a37aef0c2e58415d4bbe5d4a1f06a3a3dc78e2a436628f0d5ab9d06c5926c03b45ffbd831fbf00e825df1c81b5b99850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb5bf04de94957a0163765f43b.png)

**Comment by dimasciput** [comment]
That's from geonode, we just need to put icon for the groups.

**Comment by gubuntu** [comment]
That's just a content thing right?

@Vince-Egan's staff can add icons in production
